### ISSUE TITLE
Complete XSD

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#101]
The XSD is currently incomplete:

- [x] Missing attributes
- [x] Does not allow for tags within an `m:if` or `m:foreach`
- [ ] Add hydra tags

This is not a blocker at all, since no actual validation gets done - but the browser might complain unnecessarily.

**Comment by dirkdeyne** [comment]
Created a branch: [feature/xsd](https://github.com/medusa-ui/medusa/tree/feature/xsd)

TODO:
-  [x]  <code>eq</code> , <code>not</code> , <code>lt</code> , <code>gt</code> , ... attributes if/elseif tag
-  [x]  allow any tag in if-block (mixed)
-  [x]  rename if/elseif attribute <code>condition</code> to <code>item</code>
-  [ ] add addtional attributes to existing HTML-tags

**Comment by kevindeyne** [comment]
Task for me @kevindeyne : Push the XSD onto getmedusa.io (DNS wrap of https://raw.githubusercontent.com/medusa-ui/medusa/main/medusa-ui.xsd). Maybe something like xsd.getmedusa.io?

**Comment by dirkdeyne** [comment]
add `empty` attribute once  PR #129  is accepted.
