### ISSUE TITLE
Parameter of a click function should not assume int (vs long)

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#168]
Simple way to reproduce this is:

Controller/Eventhandler with method:

    public void load(long id) {
        System.out.println("Load: " + id);
    }

Then in the HTML file:

    <a href="#" m:click="load(16481396653467)">Load a long</a>

And you get a NumberFormatException, due to it assuming it's an int. This is likely not helped due to the lack of proper numerical types on JS side.

**Comment by dirkdeyne** [comment]
@kevindeyne see PR: #178

To distinguish a long from an int the SpelExpressionParser extra info about the number:
- 1 is considered an int
- 1l or 1L a long
- 1d or 1D a double
- 1f or 1F a float

Prior to `Merge pull request`: Make sure you have a look at the changes made on the JS side!  ;-)
