### ISSUE TITLE
Rewrite: click event

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#245]
We will need a custom tag for a click event.

This wraps the following function:
`onclick="_M.doAction(_wrapping_fragment_, 'myAction()')"`

_wrapping_fragment is filled up by the time of rendering. If there is no wrapping fragment, it's null.

In Medusa 0.x this worked like `m:change="increaseCounter(1, 'ABC')`

The goal is to be able to reference a method on the controller side directly. 

- [x] Should be able to refer to a method without parameter `doAction()`
- [x] Should be able to add parameters to the method `doAction(1, 'ABC')`
- [x] Should be able to refer to other values (ie if I click, send the value of an input field as parameter); I have no requirement on how to refer to this, my suggestion would be `doAction(#mySearchField, 123)`
-  ~~A common pattern is to disable a button after button press until the message is resolved, to prevent double-clicking to fire an event twice. Perhaps this should be an option with this default on?~~

**Comment by kevindeyne** [comment]
Re: disable button. I agree that this actually probably makes more sense with form submits. I've moved it there.

**Comment by dirkdeyne** [comment]
Ref PR #274
