### ISSUE TITLE
Rewrite: onenter

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#247]
We will need a custom tag for a onenter event.

In Medusa 0.x this worked like `m:click="increaseCounter(1, 'ABC')`

The goal is to be able to reference a method on the controller side directly. 

- [ ] Should be able to refer to a method without parameter `doAction()`
- [ ] Should be able to add parameters to the method `doAction(1, 'ABC')`
- [ ] Should be able to refer to other values (ie if I click, send the value of an input field as parameter); I have no requirement on how to refer to this, my suggestion would be `doAction(#mySearchField, 123)`
- [ ] Should be able to refer to your own value  `doAction(this.value, 123)`, again - not sure what the best way to write this would be

**Comment by dirkdeyne** [comment]
Add extra JS? [rewrite-1.0.0-onenter](https://github.com/medusa-ui/medusa/tree/rewrite-1.0.0-onenter)

Given
```html
<input id="search_enter" m:enter="search(:{#search_enter})" type="text" >
```

Result
```html
<input id="search_enter" type="text" onkeypress="if(event.key === 'Enter') { _M.doAction(null, `search('${document.querySelector('#search_enter').value}')`) }">
```

**Comment by dirkdeyne** [comment]
See PR #310 

A cleaner solution then [rewrite-1.0.0-onenter](https://github.com/medusa-ui/medusa/tree/rewrite-1.0.0-onenter)
Calls JS-function `doActionOnKeyUp`

- [x] Should be able to refer to a method without parameter `doAction()`
- [x] Should be able to add parameters to the method `doAction(1, 'ABC')`
- [x] Should be able to refer to other values (ie if I click, send the value of an input field as parameter); I have no requirement on how to refer to this, my suggestion would be `doAction(:{#mySearchField}, 123)`
- [x] Should be able to refer to your own value  `doAction(:{this}, 123)`, again - not sure what the best way to write this would be
