### ISSUE TITLE
XMLUnit and HTML

### ISSUE THREAD

**Issue by dirkdeyne** [medusa-ui/medusa#253]
XMLUnit throws errors with valid HTML5 
Example: _`XMLUnitException: The element type "br" must be terminated by the matching end-tag "</br>".`_
idem for `link`, `img`, `hr`, ...

Same problem for attributes without a value like `<input disabled />`

**Comment by kevindeyne** [comment]
Sounds like something jTidy might be able to help with.

**Comment by dirkdeyne** [comment]
Used JSoup to convert templates to XHTML: [convertToXHTML](https://github.com/medusa-ui/medusa/blob/98d99cf89e28bc358b996dcd3c0f9b32792726b6/medusa-ui/src/main/java/io/getmedusa/medusa/core/render/Renderer.java#L54)
