### ISSUE TITLE
DiffEngine does not correctly handle changes in m:event

### ISSUE THREAD

**Issue by dirkdeyne** [medusa-ui/medusa#278]
Given
```html
  <div th:text="${counterValue}"></div>
  <button m:click="increaseCounterWith(${counterValue})">Diff bug?</button>
```
And
```java

public List<Attribute> setupAttributes(ServerRequest serverRequest, Session session) {
    List<Person> people = new ArrayList<>();//generateListOfPeople();
    return List.of(new Attribute("counterValue", 0));
}

public List<Attribute> increaseCounterWith(Integer increaseWith) {
    this.counter += increaseWith;
    return List.of(new Attribute("counterValue", counter));
}
```

We get a warning like

> [WARN] i.g.m.core.diffengine.DiffEngine - comparisonToDiff: no match for comparison: Expected attribute value '_M.doAction(null, `increaseCounterWith(0)`)' but was '_M.doAction(null, `increaseCounterWith(1)`)' - comparing <button onclick="_M.doAction(null, `increaseCounterWith(0)`)"...> at /html[1]/body[1]/button[2]/@onclick to <button onclick="_M.doAction(null, `increaseCounterWith(1)`)"...> at /html[1]/body[1]/button[2]/@onclick.........

Reference: [HelloWorldController](https://github.com/medusa-ui/medusa/blob/ad4c02da2464191794251653a514c1827d9c386d/medusa-ui/src/main/java/io/getmedusa/medusa/sample/HelloWorldController.java#L47) and [hello-world.htm](https://github.com/medusa-ui/medusa/blob/ad4c02da2464191794251653a514c1827d9c386d/medusa-ui/src/main/resources/pages/hello-world.html#L12)

**Comment by kevindeyne** [comment]
We had not yet encountered 'attribute value change' diffs, so I implemented them!
