### ISSUE TITLE
Nested for loops are confused by "each"

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#41]
Our general loops work fine:
```
[$foreach $history]
<p>[$each]</p>
[$end for]
```

But once nested, the loop won't understand which each is being referred to any more:

```
[$foreach $history]
<p>[$each]</p>
   [$foreach $history2]
     <p>[$each]</p>
   [$end for]
[$end for]
```

My suggestion would be for normal loops to become:
```
[$foreach $history]
<p>[$this.each]</p>
[$end for]
```
And nested loops can become something like this:

```
[$foreach $history]
<p>[$this.each]</p>
   [$foreach $history2]
   <p>[$parent.each]</p>
   <p>[$this.each]</p>
   [$end for]
[$end for]
```

**Comment by dirkdeyne** [comment]
Currently, there is something wrong with 'single' loops, in combination with m-click-events.
Look at this simple failing [demo](https://github.com/medusa-ui/medusa/tree/bug/for-each-confusion).

Needs some further examination to find the cause...

**Comment by kevindeyne** [comment]
This is due to #8, in a way.

Basically what happens now is it assigns an ID to each conditional block. That ID is determined by the inner-block's value. 

Block: `[$foreach $first]<li>[$each]</li>[$end for]`
Inner block: `<li>[$each]</li>`

Since all blocks are the same internally ( `<li>[$each]</li>`) they produce the same id. This makes the system confused when it does a lookup of what's changed.

I applied a 'fix' to your bug branch: the value is now generated based on the entire conditional block instead of only the inner block. At least then it should have the condition itself to base the value on, which should at least make that more unique. And if the block occurs multiple times (as is the case), those have the same value (because both should change). I think that makes sense?

**Comment by kevindeyne** [comment]
Rewrote the rendering part several times, I think I have a good solution now. I've also included functionality for calling [$this.each] and [$parent.each] on the backend side.

I have not done any work yet on the JS side, so the iterations don't change yet upon variable change. That'll be for tomorrow.
