### ISSUE TITLE
nested foreach

### ISSUE THREAD

**Issue by dirkdeyne** [medusa-ui/medusa#58]
In [feature/nested-each](https://github.com/medusa-ui/medusa/tree/feature/nested-each)

Initial rendering for basic `nested-for-each`  fails (on open page)
```html
<div><button m-click="refresh()">Refresh</button></div>
<div>
    [$foreach $outer]
        [$foreach $inner]
             [$parent.each] - [$each]
        [$end for]
    [$end for]
</div>
``` 
Given 2 identical lists `$outer`  and `$inner`  with  `(1,2)`  we expect an output like:
```
1 - 1
1 - 2
2 - 1
2 - 2
```
But is
```
1 - 1
2 - 2
1 - 1
2 - 2
```
After an `m-click="refresh()"` and basically returning the same data the output is OK

**Comment by dirkdeyne** [comment]
Bug is maybe more obvious when the size of the inner loop is greater than the outer loop

```java
List<Integer> outer = new ArrayList<>(Arrays.asList(1));
List<Integer> inner = new ArrayList<>(Arrays.asList(2,3));
```

ref: commit/push bug => http://localhost:8080/bug/nested-each

> java.lang.IndexOutOfBoundsException: Calling a nested loop each via [parent], but index [1] does not reach that far.
	at io.getmedusa.medusa.core.injector.tag.IterationTag.parseEach(IterationTag.java:112)
	at io.getmedusa.medusa.core.injector.tag.IterationTag.turnTemplateIntoDiv(IterationTag.java:69)
	at io.getmedusa.medusa.core.injector.tag.IterationTag.buildBlockReplacement(IterationTag.java:53)
	at io.getmedusa.medusa.core.injector.tag.IterationTag.injectWithVariables(IterationTag.java:32)

**Comment by kevindeyne** [comment]
Welp, that's going to be a problem without an easy fix. I think I misjudged how well the parent lookup worked.
I started a rewrite (reusing a lot of elements, but just starting from scratch to rethink how I do things) in [feature/nested-each-rewrite](https://github.com/medusa-ui/medusa/pull/59)
