### ISSUE TITLE
Integration test fail  with spring-boot-starter-parent 3.3.0.

### ISSUE THREAD

**Issue by dirkdeyne** [medusa-ui/medusa#689]
Integration tests fail when upgrading [org.springframework.boot:spring-boot-starter-parent](https://github.com/spring-projects/spring-boot) from 3.2.5 to 3.3.0.

ref: #688

**Comment by kevindeyne** [comment]
This should be fixed now. There's a new thing in Selenium called 'Selenium Manager' which essentially now also does what WebDriverManager does. I guess they conflicted with each other. We don't actually need both any more, so we can just simplify the dependencies to just selenide, which pulls in selenium and lets its manager take care of downloading the driver.
